name: Auto Commit recommend.json

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/data/recommend.json'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ GH_PAT → GITHUB_TOKEN 으로 교체
          persist-credentials: false

      - name: Commit recommend.json changes
        run: |
          git config --global user.name "sanghyun412"
          git config --global user.email "sanghyun@example.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sanghyun412/jolapp-auto.git
          git add src/data/recommend.json
          git commit -m "auto: update recommend.json" || echo "No changes to commit"
          git push
